"""
Setup mobile .env.development by fetching values from GCP Secret Manager.

Usage:
    uv run python dev-tools/setup_mobile_env.py           # Normal run
    uv run python dev-tools/setup_mobile_env.py --force   # Overwrite existing

Requirements:
    - gcloud CLI authenticated: gcloud auth application-default login
    - IAM role: roles/secretmanager.secretAccessor
"""

import argparse
import sys
from pathlib import Path

try:
    from google.cloud import secretmanager
except ImportError:
    print("❌ Missing dependency: google-cloud-secret-manager")
    print("\n💡 Install: uv pip install google-cloud-secret-manager")
    sys.exit(1)

REPO_ROOT = Path(__file__).parent.parent
ENV_FILE = REPO_ROOT / "mobile" / ".env.development"
PROJECT_ID = "hikes-482104"

# Secret Manager name → .env variable name
SECRET_MAPPINGS = {
    "st_github_EXPO_PUBLIC_API_URL": "EXPO_PUBLIC_API_URL",
    "st_github_EXPO_PUBLIC_FIREBASE_API_KEY": "EXPO_PUBLIC_FIREBASE_API_KEY",
    "st_github_EXPO_PUBLIC_FIREBASE_APP_ID": "EXPO_PUBLIC_FIREBASE_APP_ID",
    "st_github_EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID": "EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
    "firestore-project-id": "EXPO_PUBLIC_FIREBASE_PROJECT_ID",
    "skane-trails_oauth_client_id": "EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID",
}

# Values derived from the Firebase project ID
DERIVED_VALUES = {
    "EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN": "{project_id}.firebaseapp.com",
    "EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET": "{project_id}.firebasestorage.app",
}


def fetch_secret(client: secretmanager.SecretManagerServiceClient, secret_name: str) -> str | None:
    """Fetch latest version of a secret."""
    name = f"projects/{PROJECT_ID}/secrets/{secret_name}/versions/latest"
    try:
        response = client.access_secret_version(request={"name": name})
        return response.payload.data.decode("UTF-8").strip()
    except Exception as e:
        print(f"  ⚠️  Could not fetch {secret_name}: {e}")
        return None


def main() -> None:
    parser = argparse.ArgumentParser(description="Setup mobile .env.development from Secret Manager")
    parser.add_argument("--force", action="store_true", help="Overwrite existing .env.development")
    args = parser.parse_args()

    if ENV_FILE.exists() and not args.force:
        print(f"✅ {ENV_FILE.relative_to(REPO_ROOT)} already exists. Use --force to overwrite.")
        sys.exit(0)

    print(f"🔑 Fetching secrets from project {PROJECT_ID}...")
    client = secretmanager.SecretManagerServiceClient()

    env_vars: dict[str, str] = {}

    # Fetch from Secret Manager
    for secret_name, env_var in SECRET_MAPPINGS.items():
        value = fetch_secret(client, secret_name)
        if value:
            env_vars[env_var] = value
            print(f"  ✅ {env_var}")
        else:
            print(f"  ⏭️  {env_var} (skipped)")

    # Derive values from project ID
    project_id = env_vars.get("EXPO_PUBLIC_FIREBASE_PROJECT_ID", PROJECT_ID)
    for env_var, template in DERIVED_VALUES.items():
        env_vars[env_var] = template.format(project_id=project_id)
        print(f"  ✅ {env_var} (derived)")

    # Write .env.development
    lines = ["# Auto-generated by dev-tools/setup_mobile_env.py", "# DO NOT COMMIT THIS FILE", ""]
    for env_var, value in env_vars.items():
        lines.append(f"{env_var}={value}")

    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"\n✅ Written to {ENV_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
