terraform {
  required_version = ">= 1.12"

  # Backend configuration is in backend.tf (generated by bootstrap in init/)
  # Run the bootstrap first: cd init/ && terraform init && terraform apply

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 7.10.0"
    }
  }
}

provider "google" {
  project = var.project
  region  = var.region
}

# IAM module - Grant permissions to users and service accounts
module "iam" {
  source = "../../modules/iam"

  project = var.project
  users   = var.users
}
