name: Auto-label PRs
on:
  pull_request:
    types: [opened, synchronize, ready_for_review, edited]

jobs:
  auto-labeling:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Based on PR Templates
        if: github.event.action == 'opened' || github.event.action == 'edited'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            const currentLabels = context.payload.pull_request.labels.map(label => label.name);

            const semverSectionMatch = body.match(/##\s*\[?SemVer\]?[\s\S]*$/i);
            const semverSection = semverSectionMatch ? semverSectionMatch[0] : "";

            const breakingCheckboxPattern = /- \[(x|X)\] This PR introduces \*\*breaking\*\* changes/;
            const hasBreakingCheckbox = breakingCheckboxPattern.test(semverSection);

            const labels = [];

            if (body.includes('<!-- Feature Addition Template,')) {
              labels.push('✨ type: enhancement');
            }
            if (body.includes('<!-- Bug Fix Template,')) {
              labels.push('🪲 type: bug');
            }
            if (body.includes('<!-- Refactor Template,')) {
              labels.push('♻️ type: refactor');
            }
            if (body.includes('<!-- Documentation Template,')) {
              labels.push('📝 type: documentation');
            }
            if (hasBreakingCheckbox) {
              labels.push('⚠️ BREAKING');
            }

            const newLabels = labels.filter(label => !currentLabels.includes(label));

            if (newLabels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: newLabels
              });
            }

      - name: Based on files changed
        if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'ready_for_review'
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          configuration-path: .github/labeler.yml
